# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers --------------------------------------
left_finger_controller:
  type: position_controllers/JointPositionController
  joint: left_finger_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
