# config/controller.yaml
controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50

    left_finger_controller:
      type: effort_controllers/JointPositionController
      joint: left_finger_joint
      pid: {p: 100.0, i: 0.01, d: 10.0}
