# Hardware configuration for real OnRobot 2FG7 gripper
onrobot_2fg7_hardware:
  ros__parameters:
    gripper_ip: "192.168.1.100"  # IP assigned by Compute Box
    gripper_port: 502
    update_rate: 10.0

    left_finger_controller:
      type: effort_controllers/JointPositionController
      joint: left_finger_joint
      pid: {p: 100.0, i: 0.01, d: 10.0}